name: Build Artifacts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        EVENT: test-workflow
        ORG: harikae86
        REPO: vue-beer-explorer
      run: |
        echo '{"event_type": "test-workflow"}' > event.json
        curl -X POST -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          -d @event.json \
          "https://api.github.com/repos/${ORG}/${REPO}/dispatches?delay=10m"