name: Build Artifacts

on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Get last workflow run time
      id: last_run_time
      run: |
        LAST_RUN_TIME=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" "https://api.github.com/repos/harikae86/vue-beer-explorer/actions/workflows/demo.yml/runs?per_page=1&status=completed&event=repository_dispatch&branch=master" | jq -r '.workflow_runs[0].created_at')
        echo "last_run_time=$LAST_RUN_TIME" >> $GITHUB_OUTPUT
      shell: bash
    - name: print last run time
      run: echo $LAST_RUN_TIME
    - name: Check time difference
      id: check_time_diff
      run: |
        LAST_RUN_TIME=$INPUT_LAST_RUN_TIME
        CURR_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        TIME_DIFF=$((($(date -ud $CURR_TIME +'%s') - $(date -ud $LAST_RUN_TIME +'%s'))/60))
        echo "time_diff=$TIME_DIFF" >> $GITHUB_ENV
        echo "time_diff: $TIME_DIFF"
        echo "last_run_time: $INPUT_LAST_RUN_TIME"
        echo ${{ env.time_diff > 5 }} 
      shell: bash
      env:
        INPUT_LAST_RUN_TIME: ${{ steps.last_run_time.outputs.last_run_time }}
    - name: Trigger main workflow
      if: ${{ env.time_diff > 5 }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        EVENT: test-workflow
        ORG: harikae86
        REPO: vue-beer-explorer
      run: |
        echo ${{ env.time_diff }}
        curl -d '{"event_type": "delay", "client_payload": {"delay": "10m"}}' -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
